---
- name: update
  apt:
    update_cache=yes
  tags:
    - update apt

- name: NGINX | Install NGINX
  apt:
    name: nginx
    state: latest
  tags:
    -nginx-package

- name: NGINX | Create NGINX config file from template
  template:
    src: files/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags:
    - nginx-configuration

